### ISSUE TITLE
Remove @everyone and @roles from allowed_mentions by default.

### ISSUE THREAD

**Issue by foopub** [git-bruh/matrix-discord-bridge#6]
Add `allowed_mentions = discord.AllowedMentions(everyone=False, roles=False)` as the default to prevent abuse. 

https://github.com/git-bruh/matrix-discord-bridge/blob/4b876734bb0dce316e7b828b1816e8928a6695c1/bridge/bridge.py#L196

**Comment by git-bruh** [comment]
The mentions are disabled here already: https://github.com/git-bruh/matrix-discord-bridge/blob/main/bridge/bridge.py#L65
