### ISSUE TITLE
Install Instructions Unclear for appservice

### ISSUE THREAD

**Issue by SIR-unit** [git-bruh/matrix-discord-bridge#7]
I'm trying to get the appservice to work, and I don't know what the various tokens are:

`as_token` - bot token?
`hs_token` - ???
`discord_token` - my user's discord token?

Basically, there are three token slots, and I only know of two tokens.

**Comment by git-bruh** [comment]
Hi, I've pushed a commit clarifying everything in the README. Quoting the relevant parts:

> as_token: The token sent by the appservice to the homeserver with events.

> hs_token: The token sent by the homeserver to the appservice with events.

> discord_token: The Discord bot's token.

> Both as_token and hs_token MUST be the same as their values in appservice.yaml. Their value can be set to anything, refer to the spec.��

**Comment by SIR-unit** [comment]
Thanks, the README is much more clear now
